Repository SteelRidgeRobotics/2025Reefscape, pull requests merged in 2025-02, with the labels that each got.

#23 Added second pivot motor
  constants.py
  subsystems/pivot.py
Labels: feature

#34 Ignore hardware limits for intake control request
  subsystems/intake.py
Labels: bug

#37 Named commands
  robot_container.py
  subsystems/climber.py
Labels: feature

#29 Added limelights and fixed pathfinding
  deploy/pathplanner/paths/Coral A.path
  deploy/pathplanner/paths/Coral B.path
  deploy/pathplanner/paths/Coral C.path
  deploy/pathplanner/paths/Coral D.path
  deploy/pathplanner/paths/Coral E.path
  deploy/pathplanner/paths/Coral F.path
  deploy/pathplanner/paths/Coral G.path
  deploy/pathplanner/paths/Coral H.path
  deploy/pathplanner/paths/Coral I.path
  deploy/pathplanner/paths/Coral J.path
  deploy/pathplanner/paths/Coral K.path
  deploy/pathplanner/paths/Coral L.path
  deploy/pathplanner/paths/Coral Station 1.path
  deploy/pathplanner/paths/Coral Station 2.path
  robot.py
  robot_container.py
  robot_state.py
  subsystems/swerve.py
Labels: bug, feature

#42 GRAAAAAAH VOLTAGE REQUESTS + ADDED CONSTANTS
  constants.py
  subsystems/climber.py
  subsystems/elevator.py
  subsystems/funnel.py
  subsystems/pivot.py
Labels: feature
